[project]
name = "pydsa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pytest-watcher>=0.4.3",
    "pytest>=8.3.3",
]